### ISSUE TITLE
python client downloader

### ISSUE THREAD

**Issue by white-gecko** [dbpedia/databus-python-client#2]
Currently the downloader returns TODO

```
$ databusclient download https://databus.coypu.org/narndt/coypu/example/
TODO
```

Are there any plans to support it? Currently also in the `client.py` there is no code for the downloader. Where would one find the relevant code in scala or what would one need to implement to support it?

**Comment by white-gecko** [comment]
It is no longer TODO but still does not download a dataset:

```
$ databusclient download https://databus.dbpedia.org/ontologies/babelnet.org/rdf/2022.11.27-025337 --localdir . --databus https://databus.dbpedia.org/
dataId not supported yet
```

**Comment by JJ-Author** [comment]
ok it seems to support either a custom SPARQL queries or download of a set of collections at the moment.
added another issue #6  to specify what is missing.
would close this issue can make new ones when they are more specific.
